### ISSUE TITLE
How to add include dirs?

### ISSUE THREAD

**Issue by LIMPIX31** [someone13574/zed-verilog-extension#8]
LSP cannot locate include files.

#### Project structure
```
core/
  top.sv
include/
  hdmi/
    macros.svh
```

#### `veridian.yml`
```yml
source_dirs:
  - core

include_dirs:
  - include

verilator:
  syntax:
    enabled: true
    args:
      - -f verilator/dev.f
```

#### HDL
```
`include "hdmi/macros.svh"
```

#### Error
```
slang: 'hdmi/macros.svh': No such file or directory
```
